language: cpp
addons:
  postgresql: 9.6
services:
  redis
jobs:
  include:
    - os: linux
      dist: trusty
      compiler:
       - gcc
      addons:
        apt:
          packages:
            - libx11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
      script: "env"
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libx11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
      script: "env"

    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - libx11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
      script: "env"

