sudo: required
env:
  global:
  - MOZ_HEADLESS=1
language: python
dist: bionic
addons:
  chrome: stable
  firefox: latest
services:
- xvfb
before_install:
- if ! [ -f ./rxwt/webtestit ]; then wget --no-check-certificate --force-directories
  -O rxwt/webtestit https://www.ranorex.com/wp-json/sage/v2/webtestit/app-download/?platform=linuxAppImage;
  fi
- sudo apt-get install desktop-file-utils
- sudo apt-get install python3-venv -y
- sudo apt-get install python3-pip -y
- sudo apt-get install openjdk-11-jdk -y
- sudo apt-get install libsecret-1-0 -y
- chmod a+x ./rxwt/webtestit
install:
- python3 -m venv .
- pushd bin && which pip3 | xargs ln -s && popd
script: "./rxwt/webtestit run ."
cache:
  directories:
  - "$TRAVIS_BUILD_DIR/rxwt/"
notifications:
  slack:
    secure: tfaacUayz+dVGzLylWiGuvGMmLB8MdUhhXeNl1y/3t8BlqFdMuNnda/YG+nNjA/Wg76Oco6rxLIPq/3IyIj8ae03VEXdbHcQwJv8s5eF8m3jacUiow7WBqNNKHrIa+mcdkmvCLBE+ChF1KUIGL6DFRIn0NitO8q+FAOh2m+YQKqppyLQZYLYl47u8fuscyc/C6L5jfRhY+9my1JD/50KBotJl1aA347b7yNU5sszM8JJJbXYUAcjDYJF5xxGS5Ygpu3zsZLpHWxJi1nO27Gd/NSPmBrOf0T74vFUjI9t9cVfDdpFAfSm/jkH/0Fc/nrp9wrPaLWFOlJFpx/fIMu/wXnwLEjHbgWgsvOXPP/O1L7EFJvhNNLD3JIK/N/tTuUwMsZ/EvlW5fIB7yQv9kRZ9F5XPPC+WsDBCvCZWY/3zZOyIjhdVFzEOoMK73ZJorcTj+uooqEFQA5NTq83/D3UnNME4s7q+2+waFKGUXHqTChulX8xSXPZ7TdhMw7FeFOQ47ZME7ZV7qK4bwhr0XfGtVqgCYqmKbOgK1xDocnXo0yvBvJQuPNxQxv9JtEvE6UI4mFSBrBMpEShG42Mb5BAe1SYKQ+YSPH7ut5kXyXKWqLCuDb6Q0XmXYG346uuGVZU4t4SW4SPEpbfc18nfvr4mu6sFWRq96Djequr0ikCZ1Q=
    - "Assembla WebApp Automation:\nBuild: <%{build_url}|#%{build_number}>\nResult: %{result} in %{duration}"
