language: cpp
jobs:
  include:
    - os: linux
      compiler:
       - gcc
      addons:
        apt:
          packages:
            - libx11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
      script: make
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libx11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
      script: make

